palette:
  top: '#8e050f'
  bottom: '#c3201d'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#b31900'
logo: 'public://color/bartik-6ad3fb0f/logo.svg'
stylesheets:
  - 'public://color/bartik-6ad3fb0f/colors.css'
files:
  - 'public://color/bartik-6ad3fb0f/logo.svg'
  - 'public://color/bartik-6ad3fb0f/colors.css'
