palette:
  top: '#128e05'
  bottom: '#1dc322'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#035900'
logo: 'public://color/bartik-6776154f/logo.svg'
stylesheets:
  - 'public://color/bartik-6776154f/colors.css'
files:
  - 'public://color/bartik-6776154f/logo.svg'
  - 'public://color/bartik-6776154f/colors.css'
