palette:
  top: '#8e8805'
  bottom: '#c3b71d'
  bg: '#ffffff'
  sidebar: '#f6f6f2'
  sidebarborders: '#f9f9f9'
  footer: '#292929'
  titleslogan: '#fffeff'
  text: '#3b3b3b'
  link: '#b3b000'
logo: 'public://color/bartik-09bd54bf/logo.svg'
stylesheets:
  - 'public://color/bartik-09bd54bf/colors.css'
files:
  - 'public://color/bartik-09bd54bf/logo.svg'
  - 'public://color/bartik-09bd54bf/colors.css'
